/// Generated by AssetsRefGenerator on 2020/05/08
class Res {
  static const String breakfast = "images/breakfast.jpg";
  static const String chappathi = "images/chappathi.jpg";
  static const String chicken_biryani = "images/chicken_biryani.jpg";
  static const String chicken_fried_rice = "images/chicken_fried_rice.png";
  static const String chicken_noodles = "images/chicken_noodles.jpg";
  static const String dosa = "images/dosa.jpg";
  static const String egg_fried_rice = "images/egg_fried_rice.jpg";
  static const String egg_noodles = "images/egg_noodles.jpg";
  static const String evening_snacks = "images/evening_snacks.jpg";
  static const String idly = "images/idly.jpg";
  static const String lunch = "images/lunch.jpg";
  static const String meals = "images/meals.jpg";
  static const String paratha = "images/paratha.jpg";
  static const String peclogo = "images/peclogo.png";
  static const String poori = "images/poori.jpg";
  static const String vada = "images/vada.jpg";
  static const String veg_fried_rice = "images/veg_fried_rice.jpg";
  static const String veg_noodles = "images/veg_noodles.jpg";
}
